import os
import json
import sys

# Path jahan story save hoti hai
STORY_JSON_PATH = os.path.join(os.path.dirname(__file__), "..", "output", "story.json")
VIDEO_FILE_PATH = os.path.join(os.path.dirname(__file__), "..", "output", "final_video.mp4")

# Check karo ki kya video aur data available hai
if not os.path.exists(STORY_JSON_PATH):
    print(f"ERROR: metadata file not found at {STORY_JSON_PATH}. Cannot upload.")
    sys.exit(1)

# Gemini ka save kiya hua raw data read karo
print("Loading viral metadata generated by Gemini...")
with open(STORY_JSON_PATH, "r", encoding="utf-8") as f:
    story_data = json.load(f)

# Naye fields extract karo
viral_title = story_data.get("title", "Amazing Cartoon Story 🦊")
seo_description = story_data.get("description", "Watch this cute moral story!")
trending_tags = story_data.get("tags", ["kids cartoon", "shorts", "moral stories"])

print(f"✨ Ready to upload with Viral Metadata:")
print(f"   -> Title: {viral_title}")
print(f"   -> Tags Count: {len(trending_tags)}")

# =======================================================
# AB JAHAN TUMHARI SCRIPT MEIN UPLOAD KA LOGIC HAI:
# =======================================================
# Tumhare body/request dictionary mein parameters aise pass honge:
#
# body = {
#     'snippet': {
#         'title': viral_title,            # <-- Gemini wala Title chala gaya
#         'description': seo_description,  # <-- Gemini wali Description chali gayi
#         'tags': trending_tags,           # <-- Gemini wale 10 Tags chale gaye
#         'categoryId': '1', # Film & Animation
#     },
#     'status': {
#         'privacyStatus': 'public'  # ya 'private' jo bhi tumne set kiya ho
#     }
# }
